routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});

*/


Route::get('/inicio','InicioController@index');


Route::resource('/profesion','ProfesionController');
Route::resource('/personas','PersonasController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Personas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Personas extends Model
{
    //
}

app/Http/Controllers/PersonasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Personas;
use App\Profesion;

class PersonasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        


        $perse =  Personas::join("profesion","personas.profesion_id","=","profesion.id")
            ->select('personas.*','profesion.nombre_profesion')
            ->get();

        return view('personas.listar',compact('perse'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $prof01 = Profesion::all();
        
        return view('personas.crear',compact('prof01'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validatedata = $request->validate([
            'nombre' => 'required',
            'primer_apellido' => 'required',
            'segundo_apellido' => 'required',
            'fecha_nacimiento' => 'required',
            'edad' => 'required'
        ]);

        $vecPer = new Personas;
        $vecPer->profesion_id = $request->profesion_id;
        $vecPer->nombre = $request->nombre;
        $vecPer->primer_apellido = $request->primer_apellido;
        $vecPer->segundo_apellido = $request->segundo_apellido;
        $vecPer->fecha_nacimiento = $request->fecha_nacimiento;
        $vecPer->edad = $request->edad;
        $vecPer->estado = "ACTIVO";
        $vecPer->save();
        return redirect('/personas');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($codpersona)
    {
        $personaselec = Personas::find($codpersona);
        $suprofesion = Profesion::all();   
        $id_persona = $codpersona;
        //return view('personas.editar',['id_perito'=>$codpersona,'perselec'=>$personaselec]);//
        return view('personas.editar',compact('id_persona','suprofesion','personaselec'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $perpapailo = Personas::find($id);
        $perpapailo->profesion_id = $request->profesion_id;
        $perpapailo->nombre = $request->nombre;
        $perpapailo->primer_apellido = $request->primer_apellido;
        $perpapailo->segundo_apellido = $request->segundo_apellido;
        $perpapailo->fecha_nacimiento = $request->fecha_nacimiento;
        $perpapailo->edad = $request->edad;
        $perpapailo->save();
        return redirect('/personas');       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($idpersona)
    {
        $personaBorrada = Personas::find($idpersona);
        $personaBorrada->delete();
        return redirect('/personas');
    }
}

resources/views/personas/crear.blade.php
@extends('layouts.admin')
@section('contenedor')

<div class="row">
	<div class="col-lg-4">
		
	</div>

	<div class="col-lg-4">
		<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Crear Nueva Persona</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('personas.store')}}" method="POST">
              	@csrf
                <div class="card-body">
                  

                  <div class="form-group">
                    <label for="nombre">Nombre de la Persona</label>
                    <input type="text" class="form-control" name="nombre" id="nombre" >
                    @error('nombre')
                    <p>{{$message}}
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="primer_apellido">Primer Apellido</label>
                    <input type="text" class="form-control" name="primer_apellido" id="primer_apellido" >
                    @error('primer_apellido')
                    <p>{{$message}}
                    @enderror
                  </div>

                  <div class="form-group">
                    <label for="segundo_apellido">Segundo Apellido</label>
                    <input type="text" class="form-control" name="segundo_apellido" id="segundo_apellido" >
                    @error('segundo_apellido')
                    <p>{{$message}}
                    @enderror
                  </div>

                  <div class="form-group">
                    <label for="fecha_nacimiento">Fecha de Nacimiento</label>
                    <input type="date" class="form-control" name="fecha_nacimiento" id="fecha_nacimiento" >
                    @error('fecha_nacimiento ')
                    <p>{{$message}}
                    @enderror
                  </div>

                  <div class="form-group">
                    <label for="edad">Edad de la Persona</label>
                    <input type="text" class="form-control" name="edad" id="edad" >
                    @error('edad')
                    <p>{{$message}}
                    @enderror
                  </div>
                  <div class="form-group">
                        <label>Profesion de la Persona</label>
                        <select class="form-control" name="profesion_id">
                         @foreach($prof01 as $proform)  
                           <option value="{{$proform->id}}">{{$proform->nombre_profesion}}</option>
                         @endforeach 
                          
                        </select>
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Guardar Datos</button>
                </div>
              </form>
            </div>
	</div>
	<div class="col-lg-4">
		
	</div>

	
</div>
	

@endsection

resources/views/personas/editar.blade.php
@extends('layouts.admin')
@section('contenedor')
<div class="row">
  <div class="col-lg-4">
    
  </div>

  <div class="col-lg-4">
    <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Modificar Datos de la Persona</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('personas.update',$id_persona)}}" method="POST">
                @csrf
                @Method('PUT')
                <div class="card-body">
                  
                  
                  <div class="form-group">
                    <label for="nombre">Nombre de la Persona</label>
                    <input type="text" class="form-control" name="nombre" id="nombre" value="{{$personaselec->nombre}}" >
                  </div>
                  <div class="form-group">
                    <label for="primer_apellido">Primer Apellido</label>
                    <input type="text" class="form-control" name="primer_apellido" id="primer_apellido" value="{{$personaselec->primer_apellido}}" >
                  </div>
                  <div class="form-group">
                    <label for="segundo_apellido">Segundo Apellido</label>
                    <input type="text" class="form-control" name="segundo_apellido" id="segundo_apellido" value="{{$personaselec->segundo_apellido}}" >
                  </div>
                  <div class="form-group">
                    <label for="fecha_nacimiento">Fecha de Nacimiento</label>
                    <input type="date" class="form-control" name="fecha_nacimiento" id="fecha_nacimiento" value="{{$personaselec->fecha_nacimiento}}" >
                  </div>
                  <div class="form-group">
                    <label for="edad">Edad de la Persona</label>
                    <input type="text" class="form-control" name="edad" id="edad" value="{{$personaselec->edad}}" >
                  </div>
                  
                  <div class="form-group">
                        <label>Profesion de la Persona</label>
                        <select class="form-control" name="profesion_id">
                           @foreach($suprofesion as $prof)  
                           <option value="{{$prof->id}}"  
                              @if($prof->id == $personaselec->profesion_id)
                                selected
                              @endif >
                            {{$prof->nombre_profesion}}</option>
                            @endforeach 
                   
                          
                        </select>
                      </div>


                  



                </div>


                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Grabar Modificacion</button>
                </div>
              </form>
            </div>
  </div>
  <div class="col-lg-4">
    
  </div>
 
</div>
  



@endsection

resources/views/personas/listar.blade.php
@extends('layouts.admin')
@section('contenedor')


<div align="center">
  <p>LISTAR PERSONAS</p>

</div>

  <a href="{{route('personas.create')}}">INGRESAR NUEVA PERSONA</a>  
  <br> </br>
  <br> </br>


<div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title"></h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    

                    <div class="input-group-append">
                      
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 700px;">
            <table class="table table-head-fixed text-nowrap">
              <thead>
              <tr>
                <th>ID</th>
                <th>NOMBRE PERSONA</th>
                <th>APELLIDO PATERNO</th>
                <th>APELLIDO MATERNO</th>
                <th>FECHA DE NAC.</th>
                <th>EDAD</th>
                <th>PROFESION</th>
                <th>ESTADO</th>
                <th>OPCIONES</th>
              </tr>
              </thead>
            <tbody>
          @foreach($perse as $personalistar)
          <tr>
            <td>{{$personalistar->id}}</td>
            <td>{{$personalistar->nombre}}</td>            
            <td>{{$personalistar->primer_apellido}}</td>            
            <td>{{$personalistar->segundo_apellido}}</td>            
            <td>{{$personalistar->fecha_nacimiento}}</td>            
            <td>{{$personalistar->edad}}</td>            
            <td>{{$personalistar->nombre_profesion}}</td>            
            <td>{{$personalistar->estado}}</td>            
            <td><a href="{{route('personas.edit',$personalistar->id)}}" class="btn btn-block    bg-gradient-primary">Editar</a>
              

              <form action="{{route('personas.destroy',$personalistar->id)}}" method="POST">
                @csrf
                @Method('DELETE')
                <input type="submit" name="eliminar" value="Eliminar" class="btn btn-block bg-gradient-danger">
              </form>
             </td>           
          </tr>
          @endforeach
               
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>

@endsection