routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});

*/


Route::get('/inicio','InicioController@index');


Route::resource('/profesion','ProfesionController');
Route::resource('/personas','PersonasController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Profesion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profesion extends Model
{
    protected $table ='profesion';

}

app/Http/Controllers/ProfesionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Profesion;

class ProfesionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        
        $profesionvar =  Profesion::all();

        return view('profesion.listar',compact('profesionvar'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('profesion.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validatedata = $request->validate([
            'nombre_profesion' => 'required|unique:Profesion'
        ]);
        $Prof = new Profesion;
        $Prof->nombre_profesion = $request->nombre_profesion;
        $Prof->estado = "ACTIVO";
        $Prof->save();
        return redirect('/profesion');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($identificador)
    {
        $profe = Profesion::find($identificador);
        return view('profesion.editar',['id_prof'=>$identificador,'papilo'=>$profe]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $profepapailo = Profesion::find($id);
        $profepapailo->nombre_profesion = $request->nombre_profesion;
        $profepapailo->save();
        return redirect('/profesion');       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($iddelprofe)
    {
        $profesorborrado = Profesion::find($iddelprofe);
        $profesorborrado->delete();
        return redirect('/profesion');
    }
}

resources/views/profesion/crear.blade.php
@extends('layouts.admin')
@section('contenedor')

<div class="row">
	<div class="col-lg-4">
		
	</div>

	<div class="col-lg-4">
		<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Crear Nueva Profesion</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('profesion.store')}}" method="POST">
              	@csrf
                <div class="card-body">                  
                  <div class="form-group">
                    <label for="nombre_profesion">Nombre de la Profesion</label>
                    <input type="text" class="form-control" name="nombre_profesion" id="nombre_profesion" >
                    @error('nombre_profesion')
                    <p>{{$message}}
                    @enderror
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
              </form>
            </div>
	</div>
	<div class="col-lg-4">
		
	</div>

	
</div>

@endsection

resources/views/profesion/editar.blade.php
@extends('layouts.admin')
@section('contenedor')

<div class="row">
	<div class="col-lg-4">
		
	</div>

	<div class="col-lg-4">
		<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Modificar Profesion</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('profesion.update',$id_prof)}}" method="POST">
              	@csrf
              	@Method('PUT')
                <div class="card-body">                  
                  <div class="form-group">
                    <label for="nombre_profesion">Descripcion de Profesion</label>
                    <input type="text" class="form-control" name="nombre_profesion" id="nombre_profesion" value="{{$papilo->nombre_profesion}}" >
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Grabar Modificaciones</button>
                </div>
              </form>
            </div>
	</div>
	<div class="col-lg-4">
		
	</div>

	
</div>

@endsection

resources/views/profesion/listar.blade.php
@extends('layouts.admin')
@section('contenedor')


<div align="center">
  <p>LISTAR PROFESIONES</p>

</div>

  <a href="{{route('profesion.create')}}">INGRESAR NUEVA PROFESION</a>  
  <br> </br>
  <br> </br>


<div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title"></h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    

                    <div class="input-group-append">
                      
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 700px;">
            <table class="table table-head-fixed text-nowrap">
              <thead>
              <tr>
                  <th>ID</th>
                  <th>PROFESION</th>
                  <th>ESTADO</th>
                  <th>OPCIONES</th>
              </tr>
              </thead>
            <tbody>
          @foreach($profesionvar as $prof)
          <tr>
            <td>{{$prof->id}}</td>
            <td>{{$prof->nombre_profesion}}</td>            
            <td>{{$prof->estado}}</td>            
            <td><a href="{{route('profesion.edit',$prof->id)}}" class="btn btn-block    bg-gradient-primary">Editar</a>
              

              <form action="{{route('profesion.destroy',$prof->id)}}" method="POST">
                @csrf
                @Method('DELETE')
                <input type="submit" name="eliminar" value="Eliminar" class="btn btn-block bg-gradient-danger">
              </form>
             </td>           
          </tr>
          @endforeach
               
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>

@endsection